// Writes the generated reference pages in docs/reference/ from their sources: the seller door's API and its refusal
// table from contract/openapi.json (with scripts/refusal-meanings.json), the vectors from contract/vectors/, and the
// pairings from @integraledger/lcp's registry (BINDINGS).
//
// Usage: node scripts/docs.mjs           writes the pages
//        node scripts/docs.mjs --check   exits 1 if any page differs from what its sources give
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const contract = join(root, "contract");
const doc = JSON.parse(readFileSync(join(contract, "openapi.json"), "utf8"));
const meanings = JSON.parse(readFileSync(join(root, "scripts", "refusal-meanings.json"), "utf8"));
const require = createRequire(join(contract, "package.json"));
const lcp = await import(pathToFileURL(require.resolve("@integraledger/lcp")).href);

const schemas = doc.components.schemas;

function frontmatter(title, description, source) {
  return [
    "---",
    `title: ${title}`,
    `description: ${JSON.stringify(description)}`,
    "---",
    "",
    `<!-- Generated by scripts/docs.mjs from ${source}. Edit the source, then run: node scripts/docs.mjs -->`,
    "",
  ].join("\n");
}

/** A Markdown table cell: pipes escaped, newlines as spaces. */
function cell(s) {
  return String(s).replaceAll("|", "\\|").replaceAll("\n", " ");
}

/** Prose for Markdown and MDX: outside code spans, <, >, { and } are written as character references. */
function prose(s) {
  return String(s)
    .split(/(`[^`]*`)/)
    .map((part, i) =>
      i % 2 === 1 ? part : part.replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("{", "&#123;").replaceAll("}", "&#125;"),
    )
    .join("");
}

function code(s) {
  const text = String(s);
  const fence = text.includes("`") ? "`` " : "`";
  return `${fence}${text}${fence === "`` " ? " ``" : "`"}`;
}

function refName(ref) {
  return ref.replace("#/components/schemas/", "");
}

/** A schema's type in one line, with component references as links. */
function typeOf(s) {
  if (s === undefined || s === true || Object.keys(s).length === 0 || (Object.keys(s).length === 1 && "description" in s)) {
    return "any JSON value";
  }
  if (s.$ref) return `[${refName(s.$ref)}](#${refName(s.$ref).toLowerCase()})`;
  if (s.oneOf) return s.oneOf.map(typeOf).join(" or ");
  if (s.allOf) return s.allOf.map(typeOf).join(" and ");
  if ("const" in s) return code(JSON.stringify(s.const));
  if (s.enum) return s.enum.map((v) => code(JSON.stringify(v))).join(", ");
  if (Array.isArray(s.type)) return s.type.map((t) => code(t)).join(" or ");
  if (s.type === "array") return `array of ${typeOf(s.items)}`;
  if (s.type) return code(s.type);
  return "any JSON value";
}

/** A schema's constraints in one line. */
function constraints(s) {
  if (s === undefined) return "";
  const out = [];
  if (s.pattern) out.push(`pattern ${code(s.pattern)}`);
  if (s.format) out.push(`format ${code(s.format)}`);
  if (s.minLength !== undefined && s.maxLength !== undefined) out.push(`${s.minLength} to ${s.maxLength} characters`);
  else if (s.maxLength !== undefined) out.push(`at most ${s.maxLength} characters`);
  else if (s.minLength !== undefined) out.push(`at least ${s.minLength} character${s.minLength === 1 ? "" : "s"}`);
  if (s.minimum !== undefined && s.maximum !== undefined) out.push(`${s.minimum} to ${s.maximum}`);
  else if (s.minimum !== undefined) out.push(`at least ${s.minimum}`);
  if (s.minItems !== undefined && s.maxItems !== undefined) out.push(`${s.minItems} to ${s.maxItems} items`);
  else if (s.maxItems !== undefined) out.push(`at most ${s.maxItems} items`);
  return out.join("; ");
}

function fieldRows(s, prefix, lines) {
  const required = new Set(s.required ?? []);
  for (const [name, p] of Object.entries(s.properties ?? {})) {
    lines.push(
      `| ${code(prefix + name)} | ${cell(typeOf(p))} | ${required.has(name) ? "yes" : "no"} | ${cell(constraints(p))} | ${cell(prose(p.description ?? ""))} |`,
    );
    if (p.type === "object" && p.properties) fieldRows(p, `${prefix}${name}.`, lines);
  }
}

function fieldTable(s) {
  const lines = ["| Field | Type | Required | Constraints | Description |", "|---|---|---|---|---|"];
  fieldRows(s, "", lines);
  return lines.join("\n");
}

function schemaSection(name, s) {
  const out = [`### ${name}`, ""];
  if (s.description) out.push(prose(s.description), "");
  if (s.type === "object" || s.properties) {
    if (s.additionalProperties === false) out.push("An object. A member not listed here is refused.", "");
    else out.push("An object.", "");
    out.push(fieldTable(s), "");
  } else {
    out.push(`${typeOf(s)}${constraints(s) ? `; ${constraints(s)}` : ""}.`, "");
  }
  return out.join("\n");
}

function refusalCodes(schema) {
  return schema?.allOf?.[1]?.properties?.code?.enum;
}

function apiPage() {
  const out = [
    frontmatter(
      "Seller door API",
      "Every operation, request, answer and schema of the seller door, generated from openapi.json.",
      "contract/openapi.json",
    ),
    `# ${doc.info.title} API`,
    "",
    prose(doc.info.description),
    "",
    `- **OpenAPI:** ${doc.openapi}; document version ${code(doc.info.version)}; license ${doc.info.license.identifier}.`,
  ];
  for (const server of doc.servers) {
    const vars = Object.entries(server.variables ?? {})
      .map(([k, v]) => `${code(k)} (for example ${code(v.default)})`)
      .join(", ");
    out.push(`- **Base URL:** ${code(server.url)}${vars ? `, where ${vars} is your door's base URL` : ""}.`);
  }
  for (const [name, scheme] of Object.entries(doc.components.securitySchemes)) {
    out.push(`- **Authentication:** ${code(name)}: HTTP ${code(scheme.scheme)} with format ${code(scheme.bearerFormat)}. ${prose(scheme.description)}`);
  }
  out.push("", "## Operations", "", "| Operation | Method and path | Summary |", "|---|---|---|");
  const ops = [];
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const [method, op] of Object.entries(item)) ops.push({ path, method: method.toUpperCase(), op });
  }
  for (const { path, method, op } of ops) out.push(`| [${code(op.operationId)}](#${op.operationId}) | ${code(`${method} ${path}`)} | ${cell(prose(op.summary))} |`);
  out.push("");
  for (const { path, method, op } of ops) {
    out.push(`### ${op.operationId}`, "", `${code(`${method} ${path}`)}: ${prose(op.summary)}`, "");
    if (Array.isArray(op.security) && op.security.length === 0) out.push("No credential is required.", "");
    else out.push(`Requires the seller credential: ${code("Authorization: Bearer isk_…")}.`, "");
    for (const p of op.parameters ?? []) {
      out.push(`**Path parameter** ${code(p.name)}: ${typeOf(p.schema)}${p.required ? ", required" : ""}.`, "");
    }
    const body = op.requestBody?.content?.["application/json"]?.schema;
    if (body) out.push(`**Request body** (${code("application/json")}): ${typeOf(body)}.`, "");
    out.push("| Status | Meaning | Body | Headers |", "|---|---|---|---|");
    for (const [status, r] of Object.entries(op.responses)) {
      const schema = r.content?.["application/json"]?.schema;
      const codes = refusalCodes(schema);
      const bodyCell = codes ? `[Refusal](#refusal): ${codes.map((c) => `[${code(c)}](./refusals.md#${c.replaceAll("/", "").toLowerCase()})`).join(", ")}` : schema ? typeOf(schema) : "";
      const headers = Object.entries(r.headers ?? {})
        .map(([h, v]) => `${code(h)}: ${"const" in (v.schema ?? {}) ? code(v.schema.const) : cell(prose(v.description))}`)
        .join("; ");
      out.push(`| ${status} | ${cell(prose(r.description))} | ${cell(bodyCell)} | ${cell(headers)} |`);
    }
    out.push("");
  }
  out.push("## Schemas", "");
  for (const [name, s] of Object.entries(schemas)) out.push(schemaSection(name, s));
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

function refusalsPage() {
  const all = schemas.Refusal.properties.code.enum;
  const missing = all.filter((c) => !(c in meanings));
  const extra = Object.keys(meanings).filter((c) => !all.includes(c));
  if (missing.length > 0 || extra.length > 0) {
    throw new Error(`scripts/refusal-meanings.json: missing ${missing.join(", ") || "none"}; not in openapi.json ${extra.join(", ") || "none"}`);
  }
  const statusOf = new Map();
  const described = new Map();
  for (const item of Object.values(doc.paths)) {
    for (const op of Object.values(item)) {
      for (const [status, r] of Object.entries(op.responses)) {
        const codes = refusalCodes(r.content?.["application/json"]?.schema);
        if (!codes) continue;
        if (!described.has(status)) described.set(status, r.description);
        for (const c of codes) statusOf.set(c, Number(status));
      }
    }
  }
  const out = [
    frontmatter(
      "Refusal codes",
      "Every code the seller door refuses with, its HTTP status and what it means.",
      "contract/openapi.json and scripts/refusal-meanings.json",
    ),
    "# Refusal codes",
    "",
    `A refusal is a JSON object ${code('{"code", "sentence", "correlationId"}')}. The ${code("code")} is one of the ${all.length} below and is stable. The ${code("sentence")} is for people and may be reworded. The ${code("correlationId")} names the call in the door's log.`,
    "",
    `Every ${code("503")} answer carries ${code("Retry-After: 1")}: retry the same request after a second. Every other refusal is final for the request as sent.`,
    "",
    `The same codes are exported as ${code("REFUSALS")} from ${code("@integraledger/agentic-connectors")}, each with its status.`,
    "",
  ];
  const byStatus = new Map();
  for (const c of all) {
    const status = statusOf.get(c) ?? schemaStatus(c);
    if (!byStatus.has(status)) byStatus.set(status, []);
    byStatus.get(status).push(c);
  }
  for (const status of [...byStatus.keys()].sort((a, b) => a - b)) {
    out.push(`## ${status}`, "");
    if (described.has(String(status))) out.push(prose(described.get(String(status))), "");
    out.push("| Code | Meaning |", "|---|---|");
    for (const c of byStatus.get(status)) out.push(`| <a id="${c.replaceAll("/", "").toLowerCase()}"></a>${code(c)} | ${cell(prose(meanings[c]))} |`);
    out.push("");
  }
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

/** The status of a code no operation lists: the contract package's table. */
function schemaStatus(c) {
  const table = JSON.parse(
    readFileSync(join(contract, "src", "index.ts"), "utf8")
      .split("export const REFUSALS")[1]
      .split("Object.freeze(")[1]
      .split(");")[0]
      .replace(/,\s*}$/, "}"),
  );
  return table[c];
}

function vectorsPage() {
  const dir = join(contract, "vectors");
  const files = readdirSync(dir)
    .filter((f) => /^CV[0-9]+\.json$/.test(f))
    .sort((a, b) => Number(a.slice(2, -5)) - Number(b.slice(2, -5)));
  const out = [
    frontmatter("Vectors", "The seller door's vectors: the requests, the answers they must produce, and the ATR bytes they store.", "contract/vectors/"),
    "# Vectors",
    "",
    `Each file in ${code("contract/vectors/")} is one exchange with the seller door, with every value fixed: the tenant and its credential, the declared resources, the storage base, the clock and the ATR identifiers minted in order. Any implementation of the door, and any test double a connector uses, must give each step's answer. The package exports them as ${code("VECTORS")}. See [the vectors guide](../guides/vectors.md) for the file format and how to replay them.`,
    "",
    "| Vector | Name | Steps | Pairing |",
    "|---|---|---|---|",
  ];
  const vectors = files.map((f) => [f.slice(0, -5), JSON.parse(readFileSync(join(dir, f), "utf8"))]);
  for (const [id, v] of vectors) {
    const pairings = [...new Set(v.fixed.resources.flatMap((r) => r.pairings))];
    out.push(`| [${id}](#${id.toLowerCase()}) | ${cell(v.name)} | ${v.steps.length} | ${pairings.map(code).join(", ")} |`);
  }
  out.push("");
  for (const [id, v] of vectors) {
    out.push(`## ${id}`, "", `**${prose(v.name)}.** Source: ${prose(v.source)}`, "");
    out.push("| Step | Request | Answer | Stores |", "|---|---|---|---|");
    v.steps.forEach((s, i) => {
      const body = s.expect.body;
      const answer = typeof body === "object" && body !== null && "code" in body
        ? `${s.expect.status} ${code(body.code)}`
        : `${s.expect.status}${typeof body === "object" && body !== null && "state" in body ? ` ${code(`state: ${body.state}`)}` : ""}`;
      const agreed = s.agreed ? " (agreement recorded before it)" : "";
      const stores = s.stored ? `${Buffer.byteLength(s.stored.bytes, "utf8")} bytes, SHA-256 ${code(s.stored.sha256)}` : s.storedFiles !== undefined ? `${s.storedFiles} file(s) in storage` : "";
      out.push(`| ${i + 1} | ${code(`${s.request.method} ${s.request.path}`)}${agreed} | ${answer} | ${cell(stores)} |`);
    });
    out.push("");
  }
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

const SURFACES = {
  x402: "x402",
  mpp: "MPP",
  card: "Card",
  acp: "ACP",
  ap2: "AP2",
  ucp: "UCP",
  ack: "ACK",
};

function yes(b) {
  return b ? "yes" : "no";
}

function pairingsPage() {
  const bindings = [...lcp.BINDINGS].sort((a, b) => a.id.localeCompare(b.id));
  const out = [
    frontmatter(
      "Pairings",
      "Every pairing id the seller door accepts, with its binding pattern and what a record of it proves.",
      "the BINDINGS registry of @integraledger/lcp",
    ),
    "# Pairings",
    "",
    `A pairing names a payment protocol, scheme and rail, such as ${code("x402/exact/eip155/eip3009")}. It is the ${code("pairing")} of every offer, claim and report, and the door answers each record with the pairing's pattern. This page lists the ${bindings.length} pairings of ${code("@integraledger/lcp")}'s registry (${code("BINDINGS")}), the package that owns each binding. How the hash rides in each one is documented with that package, in [integra-protocol](https://github.com/IntegraLedger/integra-protocol).`,
    "",
    "The columns:",
    "",
    `- **Pattern:** how the pairing carries the ATR hash (the pattern's ${code("pattern")}).`,
    `- **Buyer signs:** the buyer's approval signs the hash (${code("buyerSigns")}).`,
    `- **On chain:** the hash is written on chain with the payment (${code("onChain")}).`,
    `- **Public proof:** something public carries the hash (${code("publicProof")}). Where it is "no", a seller that configures the agreement step gets one; see [the agreement step](../guides/agreement-step.md).`,
    `- **Claim:** "yes" when ${code("claim")} checks the payment; "no" when there is nothing to check and the door answers ${code("claim/nothing-to-check")}, so you report instead.`,
    `- **Push:** "yes" when the buyer broadcasts the payment before the claim, so a failed check is answered ${code("declined")}, never refused.`,
    `- **Profile:** the LCP profile that defines the binding, where one does.`,
    "",
  ];
  for (const [surface, label] of Object.entries(SURFACES)) {
    const group = bindings.filter((b) => b.id.startsWith(`${surface}/`));
    if (group.length === 0) continue;
    out.push(`## ${label}`, "", "| Pairing | Pattern | Buyer signs | On chain | Public proof | Claim | Push | Profile |", "|---|---|---|---|---|---|---|---|");
    for (const b of group) {
      const p = b.pattern;
      out.push(
        `| ${code(b.id)} | ${code(p.pattern)} | ${yes(p.buyerSigns)} | ${yes(p.onChain)} | ${yes(p.publicProof)} | ${yes(b.claims)} | ${yes(typeof b.landedTx === "function")} | ${p.profile ? code(p.profile) : ""} |`,
      );
    }
    out.push("");
  }
  const unlisted = bindings.filter((b) => !Object.keys(SURFACES).some((s) => b.id.startsWith(`${s}/`)));
  if (unlisted.length > 0) throw new Error(`pairings on no listed surface: ${unlisted.map((b) => b.id).join(", ")}`);
  out.push("## What each record proves", "", `Each record's ${code("proves.pattern.proves")} is the pairing's sentence below. A sentence with ${code("<network>")} and ${code("<transaction>")} names the agreement payment once it is recorded.`, "");
  for (const b of bindings) out.push(`- ${code(b.id)}: ${prose(b.pattern.proves)}`);
  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}

const pages = {
  "docs/reference/seller-door-api.md": apiPage(),
  "docs/reference/refusals.md": refusalsPage(),
  "docs/reference/vectors.md": vectorsPage(),
  "docs/reference/pairings.md": pairingsPage(),
};

const check = process.argv.includes("--check");
let stale = 0;
for (const [path, text] of Object.entries(pages)) {
  const file = join(root, path);
  if (check) {
    let now = "";
    try {
      now = readFileSync(file, "utf8");
    } catch {}
    if (now !== text) {
      stale++;
      console.log(`${path} differs from its sources: run node scripts/docs.mjs`);
    }
  } else {
    writeFileSync(file, text);
    console.log(`wrote ${path}`);
  }
}
if (check) console.log(stale === 0 ? `${Object.keys(pages).length} generated pages match their sources` : `${stale} page(s) stale`);
process.exit(stale === 0 ? 0 : 1);
